name: spider
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8.20
  - wheel=0.45.1=pyhd8ed1ab_0
  - pip
  - pip:
      - numpy==1.22.4
      - pandas==2.0.3
      - scipy==1.10.1
      - scikit-learn==1.3.2
      - matplotlib==3.7.5
      - scanpy==1.9.8
      - anndata==0.9.2
      - tqdm==4.67.1
      - ipykernel
prefix: /home/istiaq/anaconda3/envs/spider
